- block:
  - name: Install apache
    package:
      name: "{{ apache_package }}"
      state: latest
      update_cache: yes
 
  - name: copy archive
    copy:
      src: html.tar.gz
      dest: /tmp/

  - name: unarchive html files
    unarchive:
      src: /tmp/html.tar.gz
      dest: /var/www/
      remote_src: true

  - name: start and enable apache
    systemd:
      name: "{{ apache_package  }}"
      state: started
      enabled: yes
  when: ansible_distribution in ["Debian", "Ubuntu", "Fedora", "CentOS", "AlmaLinux"]
