---

- hosts: all
  become: true
  tasks:
    - name: "apt update"
      apt: 
        update_cache: yes
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: "install apache2 package"
      apt:
        name: apache2
        state: latest    
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: "dnf update"
      dnf: 
        update_cache: yes
        state: latest
      when: ansible_distribution in ["CentOS", "AlmaLinux"]

    - name: "install apache2(httpd) package"
      dnf:
        name: httpd
        state: latest    
      when: ansible_distribution in ["CentOS", "AlmaLinux"]
